# Matrices and Determinants

In [106]:
import numpy as np

# Matrix

In [107]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[1,4,3],[2,1,3],[2,1,1]])
# matrix_2 = np.array([[1,4,3,2],[2,1,1,3],[2,3,1,1]])
# matrix_1 = np.array([[1,4],[2,1],[3,1]])
# matrix_2 = np.full((2,3), 3)
print(matrix_1)
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 3]
 [2 1 3]
 [2 1 1]]


In [108]:
# [n]egitive [o]f [a] [m]atrix
noam_1 = matrix_1 * -1
noam_2 = matrix_2 * -1
print(noam_1)
print(noam_2)

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[-1 -4 -3]
 [-2 -1 -3]
 [-2 -1 -1]]


In [109]:
# [a]ddition [o]f [m]atrices
aom = matrix_1 + matrix_2
print(aom)

[[ 2  6  6]
 [ 6  6  9]
 [ 9  9 10]]


In [110]:
# [s]ubtraction [o]f [m]atrices
som = matrix_1 - matrix_2
print(som)

[[ 0 -2  0]
 [ 2  4  3]
 [ 5  7  8]]


In [111]:
# [m]ultiplication [o]f [a] [m]atrix [b]y [s]calar [n]umber
sclar_num = 3
moambsn_1 = matrix_1 * sclar_num
moambsn_2 = matrix_2 * sclar_num
print(moambsn_1)
print(moambsn_2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3 12  9]
 [ 6  3  9]
 [ 6  3  3]]


In [112]:
# [m]ultiplication [o]f [t]wo-D [a]rray
# This is default multiplication, it's don't even follow the matrix rule, it's face to face multiplication of numpy arrays
mota = matrix_1 * matrix_2
print(mota)

[[ 1  8  9]
 [ 8  5 18]
 [14  8  9]]


In [ ]:
# [m]ultiplication [o]f [m]atrix
def mom(matrix_a,matrix_b):
    m3 = []
    if matrix_a.shape[1] == matrix_b.shape[0]:
        for i in matrix_a:
            first_element = []
            for j in range(matrix_b.shape[1]):
                first_element.append((i * matrix_b[:,j]).sum())
            m3.append(first_element)
        return np.array(m3)
    else:
        raise AttributeError(f'Number of elments in COLUMNs of matix 1 ({matrix_a.shape[1]}) and Number of elements in ROWs of matix 2 ({matrix_b.shape[0]}) must be EQUAL')
    
print(mom(matrix_1,matrix_2))
print(mom(mom(matrix_2,matrix_1), matrix_2)) # for three matrix you can do this also you can apply loop for more matrices to multiply 

[[11  9 12]
 [26 27 33]
 [41 45 54]]
[[238 252 306]
 [171 180 219]
 [ 89  90 111]]


In [118]:
# [t]ranspose [o]f [m]atrix
# luckly we have a built in numpy method for this
tom_1 = matrix_1.transpose()
tom_2 = matrix_2.transpose()
print(tom_1)
print(tom_2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 2]
 [4 1 1]
 [3 3 1]]


In [ ]:
# check [s]ymmetric [m]atrix
def is_sm(matrix):
    if np.all(matrix.transpose() == matrix):
        return True
    else:
        return False

example_matrix = np.array([[4, 2, -1],[2, 5, 3],[-1, 3, 6]])
print(example_matrix)
print(is_sm(example_matrix))
print(is_sm(matrix_1))
print(is_sm(matrix_2))

[[ 4  2 -1]
 [ 2  5  3]
 [-1  3  6]]
True
False
False


In [125]:
# check [s]kew [s]ymmetric [m]atrix
def is_ssm(matrix):
    if np.all(matrix.transpose() == matrix * -1):
        return True
    else:
        return False

example_matrix = np.array([[0,  2, -3],[-2, 0,  4],[3, -4,  0]])
print(example_matrix)
print(is_ssm(example_matrix))
print(is_ssm(matrix_1))
print(is_ssm(matrix_2))

[[ 0  2 -3]
 [-2  0  4]
 [ 3 -4  0]]
True
False
False


# Determinate comingsoon