# Why NumPy?
NumPy arrays are the core of numerical computing in Python. They are:
 - Faster than Python lists (C-optimized)
 - Memory-efficient (store data in a contiguous block)
 - Support vectorized operations that support SIMD (no slow Python loops)
 - Used in ML, Data Science, and AI

# NumPy Arrays

##### 1. Creating arrays from list

In [ ]:
import numpy as np

arr1 = np.array([1,2,3]) # 1D array
print(arr1)

arr2 = np.array([[1,2,3], [4,5,6]]) # 2D array
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


##### 2. Creating arrays without list

In [14]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arr = np.full((4,3), 3)
print(arr)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
arr = np.eye(3) # 3x3 identity matrix
print(arr) # remember identity matrix is square matrix so only one arguement

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.arange(1,15, 3)
print(arr)
# let say this is np.arange(a, b, c)
# so it will print a then it will add c to it then print it 
# all the way to b-1
# its just like normal python range function
ran = list(range(1,15,3)) # we say this (start, stop, step)
print(ran)

[ 1  4  7 10 13]
[1, 4, 7, 10, 13]


In [ ]:
arr = np.linspace(0, 1, 9) # linspace(a, b, c) will create an 1D array of evenly divided a and b by c
print(arr)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


#### 3. Checking array propterties

In [39]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [43]:
myarr.shape
# this gives a tuple that consist (rows, colums)

(4, 3)

In [45]:
myarr.ndim
# this gives an int that tells the dimention of the array

2

In [47]:
myarr.size
# gives a int - total no of elements in the array

12

In [49]:
myarr.dtype
# tells the type of elements

dtype('int32')

#### 4. Changing data type

In [ ]:
myarr2 = np.array([[1,2,3], [4,5,6]], dtype='float32') # changing explicitly (during the making of array)
print(myarr2)
print(myarr2.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float32


In [55]:
# if the array is alreay made and then we need to change it's type
myarr2_int = myarr2.astype('int32')
print(myarr2_int)
print(myarr2_int.dtype)

[[1 2 3]
 [4 5 6]]
int32


#### 5. Reshaping and Flattening Arrays

In [60]:
myarr3 = np.array([[1,2,3], [4,5,6]])
a = myarr3.shape
print(a)

(2, 3)


In [59]:
b = myarr3.reshape((3,2)) # this will reshape the existing array by giving a tuple of size (i.e the mul of size is equal to the no of elements)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
c = myarr3.flatten() # converts 2D array to 1D
print(c)

[1 2 3 4 5 6]
