# Indexing and slicing
It is just like slicing of list in python

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [4]:
print(arr[0])
print(arr[5])

1
6


In [6]:
print(arr[3:9])

[4 5 6 7 8 9]


In [7]:
print(arr[:5]) # or arr[0:5]

[1 2 3 4 5]


In [8]:
print(arr[4:]) # or arr[4:len(arr)]

[5 6 7 8 9 0]


In [9]:
len(arr)

10

In [10]:
arr.size

10

In [ ]:
print(arr[2:8:2]) # arr[start:stop:step] same as list

[3 5 7]


In [ ]:
print(arr[::-1]) # printing reverse array

[0 9 8 7 6 5 4 3 2 1]


In [ ]:
print(arr[::2])

[1 3 5 7 9]


### Slicing returns a view, not a copy! Changes affect the original array. See example

In [ ]:
arr1 = np.array([1,24,4,51,65,33,27,0,91,13])

arr2 = arr1[3:6]
print(arr2) # make arr2 using 3 elements of arr1

arr2[0] = 555
print(arr2) # maked changes in arr2

print(arr1) # but the changes can be seen in arr1 also

# NOTE: this is becaue slicing in numpy arrays returns a preivew not a copy. So, the changes affects the original arrays too

[51 65 33]
[555  65  33]
[  1  24   4 555  65  33  27   0  91  13]


 > Use `.copy()` if you need an independent copy.


In [29]:
arr1 = np.array([1,31,22,32,45,64,23,64,2,39])

arr2 = arr1[3:6].copy()
print(arr2)

arr2[0] = 999
print(arr2)

print(arr1)

[32 45 64]
[999  45  64]
[ 1 31 22 32 45 64 23 64  2 39]


### Fancy Slicing and Boolean Masking

In [34]:
arr1 = np.array([12,32,43,342,6,2,53,435,234,3,34,84])

# you can give a list of indexs to get particualar elements from the array
print(arr1[[2,6,9]])

# you can also apply a condition and filter elements from the array
print(arr1[arr1 > 100])

[43 53  3]
[342 435 234]
