# Exercises for Practice
 - Create a 3×3 array filled with random numbers and print its shape.
 - Convert an array of floats [1.1, 2.2, 3.3] into integers.
 - Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
 - Reshape a 1D array of size 9 into a 3×3 matrix.
 - Use boolean masking to filter numbers greater than 50 in an array.

### Create a 3×3 array filled with random numbers and print its shape.


In [14]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.shape)

(3, 3)


### Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [15]:
arr_of_float = np.array([1.1, 2.2, 3.3])
arr_of_int = arr_of_float.astype('int32')
print(arr_of_float)
print(arr_of_float.dtype)
print(arr_of_int)
print(arr_of_int.dtype)

[1.1 2.2 3.3]
float64
[1 2 3]
int32


### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [16]:
natty_nums = np.array([1,2,3,4,5,6])
even_nums = natty_nums[natty_nums % 2 == 0]
print(even_nums)

[2 4 6]


### Reshape a 1D array of size 9 into a 3×3 matrix.

In [17]:
one_d = np.array([1,2,3,4,5,6,7,8,9])
print(one_d.ndim)
three_x_three = one_d.reshape((3,3))
print(three_x_three)

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Use boolean masking to filter numbers greater than 50 in an array.

In [18]:
myarr = np.array([i*10 for i in range(1,11)])
filter_fifty = myarr[myarr > 50]
print(filter_fifty)

[ 60  70  80  90 100]
