# Multidimensional Indexing and Axis
NumPy allows you to efficiently work with multidimensional arrays, where indexing and axis manipulation play a crucial role. Understanding how indexing works across multiple dimensions is essential for data science and machine learning tasks.

### Understanding Axes in NumPy
Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0.

For example:
 - **1D** array - 1 axis (axis 0)
 - **2D** array - 2 axes (axis 0 = rows, axis 1 = columns)
 - **3D** array - 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

### 2D array: Axis and indexing

In [1]:
import numpy as np

arr1D = np.array(
    [1,2,3,4]
    ) # we've seen slicing and indexing in 1D alreay. Now, 2D and 3D

print(arr1D.shape)

(4,)


In [2]:
arr2D = np.array(
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]]
)

print(arr2D.shape)

(3, 4)


In [3]:
# indexing
print(arr2D[0]) 
print(arr2D[1])
print(arr2D[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [4]:
# Slicing
print(arr2D[0][2]) # or
print(arr2D[0,2]) # and also
print(arr2D[0:2, 1:3])

3
3
[[2 3]
 [6 7]]


In [5]:
# summation along axis
print(np.sum(arr2D, axis=0))
print(np.sum(arr2D, axis=1))
# Axis 0 (rows): Operations move down the columns.
# Axis 1 (columns): Operations move across the rows.

[15 18 21 24]
[10 26 42]


### 3D array: axis and indexing

In [6]:
arr3D = np.array(
    [[[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]]
)

print(arr3D.shape)
# 3D array has deapth, rows and column

(2, 2, 3)


In [7]:
# indexing
print(arr3D[1,0,2])

# slicing
print(arr3D[:, 0, :])

9
[[1 2 3]
 [7 8 9]]


### Changing data

In [8]:
arr3D[1,0,1] = 88 # change a single element
print(arr3D)

arr3D[0,1] = [0,0,0] # change whole row
print(arr3D)

arr2D[:, 2] = 0 # change that apply to multiple rows
print(arr2D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7 88  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 0  0  0]]

 [[ 7 88  9]
  [10 11 12]]]
[[ 1  2  0  4]
 [ 5  6  0  8]
 [ 9 10  0 12]]
