### Loops are slow
This is because Python's interpreter adds overhead, making iteration less efficient.


In [67]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
result = []
for i in arr:
    result.append(i**2)
print(result)

[1, 4, 9, 16, 25, 36]


### Vectorization
It allows you to **apply operations to entire arrays at once**, greatly improving performance by utilizing NumPy’s optimized C backend.

In [68]:
arr = np.array([1,2,3,4,5,6])
result = arr ** 2
print(result)

[ 1  4  9 16 25 36]


# Broadcasting 
It enables operations between arrays of **different shapes** by automatically stretching the smaller array to match the shape of the larger array, without creating additional copies.


In [69]:
# Example 1
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [70]:
# Example 2
# axis = 0 (rows)
arr1 = np.array([1,2,3]) # shape: (1, 3)
arr2 = np.array([[4,5,6], [7,8,9]]) # shape: (2, 3)
result = arr1 + arr2
print(result)

[[ 5  7  9]
 [ 8 10 12]]


In [71]:
# Example 3
# axis = 1 (columns)
arr1 = np.array([[2], [2]]) # shape: (2, 1)
arr2 = np.array([[4,5,6], [7,8,9]]) # shape: (2, 3)
result = arr1 + arr2
print(result)

[[ 6  7  8]
 [ 9 10 11]]


### Real-world use
Broadcasting can be used in data science tasks, such as normalizing datasets, without sacrificing memory or performance.


In [72]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
# The above two lines are of Numpy's math tools, see in next lesson

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
